apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: "ASEQT6f62MNlujvz6ZXFC9BYx40v2BC/8eJZcsiEJn8/1Shn8HXfcGvyfS+O0rUI
Qtkm2/OaryPrJWp6Z6fvlA=="
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
